language: node_js
node_js:
    - "node"
    - "14"
    - "12"
    - "11"

ENV:
    - JWT_SECRET="random010232315443253random3j45jb395g4jdfg504gmdfkg53"

services: mongodb

before_script:
    - npm install

script:
    - npm test